name: Deploy to FTP

on:
  push:
    branches:
      - main  # Change to your branch if different

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload to FTP server
      uses: lukaszfiszer/ftp-deploy-action@v1.1.0
      with:
        host: ${{ secrets.FTP_HOST }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: './'  # Directory to upload, adjust if necessary
        remote-dir: '/home/vishesha/domains/vishesharya.in/public_html'
